# create your drupal and postgres config here, based off the last assignment


version: '3.1'

services:

  drupal:
    # image: drupal
    build:
      context: .
      dockerfile: drupal.Dockerfile    
    image: drupal-custom
    ports:
      - 8080:80
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drupal
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: